// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdMxvXYu8C-MjYUKEohFedWzrLk2FWO84',
    appId: '1:10268855228:web:a88741d3b10b2ca388f9b9',
    messagingSenderId: '10268855228',
    projectId: 'study-app-43a56',
    authDomain: 'study-app-43a56.firebaseapp.com',
    storageBucket: 'study-app-43a56.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQF-AiLrSnSjHtGBYFE4KgZNZCGnCVWuo',
    appId: '1:10268855228:android:f2904e73385b4c5c88f9b9',
    messagingSenderId: '10268855228',
    projectId: 'study-app-43a56',
    storageBucket: 'study-app-43a56.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL0DAGoQdtWufYKw-XVifSW_fi0pBc-zI',
    appId: '1:10268855228:ios:d7fc57b3b8c34e8188f9b9',
    messagingSenderId: '10268855228',
    projectId: 'study-app-43a56',
    storageBucket: 'study-app-43a56.appspot.com',
    iosClientId:
        '10268855228-8rrivrtmufjb2cc14hsvi50b5kn93oeq.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyngApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCL0DAGoQdtWufYKw-XVifSW_fi0pBc-zI',
    appId: '1:10268855228:ios:d7fc57b3b8c34e8188f9b9',
    messagingSenderId: '10268855228',
    projectId: 'study-app-43a56',
    storageBucket: 'study-app-43a56.appspot.com',
    iosClientId:
        '10268855228-8rrivrtmufjb2cc14hsvi50b5kn93oeq.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyngApp',
  );
}
